# database to be used for general user data of Polizei
development:
  adapter: postgresql
  host: localhost
  database: database
  port: 5432
  username: username
  password: password

# to query the redshift cluster for general information
redshift_development:
  adapter: redshift
  host: analytics-dw-1.analyticsmediagroup.net
  database: amg
  port: 5439
  username: username
  password: password
