# database to be used for general user data of Polizei
development:
  adapter: postgresql
  host: localhost
  database: database
  port: 5432
  username: username
  password: password

# to query the redshift cluster for general information
redshift_development:
  adapter: redshift
  host: cluster1.redshift.example.com
  database: amg
  port: 5439
  username: username
  password: password

# connection for running some of the rspec tests
test:
  adapter: postgresql
  host: localhost
  database: database
  port: 5432
  username: username
  password: password
redshift_test:
  adapter: redshift
  host: cluster1.redshift.example.com
  database: amg
  port: 5439
  username: username
  password: password
