job_failure_cc: admin@example.com # when a job fails, the failure email will have this cc recipient
job_failure_bcc: admin@example.com # when a job fails, the failure email will have this bcc recipient
