octopus:
  environments:
    - shards
  shards:
    postgres:
      adapter: postgresql
      host: localhost
      database: db
      port: 5432
      username:
      password:
    redshift:
      adapter: redshift
      host: host
      database: db
      port: 5439
      username:
      password:
